[build]
  command = "npm ci && npm run build && ./vendor/bin/jigsaw build production"
  publish = "build_production"

[build.environment]
  PHP_VERSION = "8.2"

[context.production]
  command = "composer install --no-dev --optimize-autoloader && npm ci && ./vendor/bin/jigsaw build production && vite build"

[context.deploy-preview]
  command = "npm ci && npm run dev && ./vendor/bin/jigsaw build"
  publish = "build_local"

[context.branch-deploy]
  command = "composer install --no-dev --optimize-autoloader && npm ci && JIGSAW_ENV=staging ./vendor/bin/jigsaw build staging && vite build"
  publish = "build_staging"