[build]
  command = "composer install --no-dev --optimize-autoloader && npm run build"
  publish = "build_production"

[context.production]
  command = "composer install --no-dev --optimize-autoloader && npm run build"
  publish = "build_production"

[context.develop]
  command = "composer install --no-dev --optimize-autoloader && npm run build:dev"
  publish = "build_local"

[context.branch-deploy]
  command = "composer install --no-dev --optimize-autoloader && npm run build:dev"
  publish = "build_local"

[build.environment]
  PHP_VERSION = "8.2"