[build]
  command = "composer install --no-dev --prefer-dist && npm run build"
  publish = "build_local"

[context.production]
  command = "composer install --no-dev --prefer-dist && npm run build"
  publish = "build_production"

[context.branch-deploy]
  command = "composer install --no-dev --prefer-dist && npm run build"
  publish = "build_local"