[build]
  command = "npm run build"
  publish = "build_production"

[context.production]
  command = "npm run build"
  publish = "build_production"

[context.develop]
  command = "npm run build:dev"
  publish = "build_local"

[context.branch-deploy]
  command = "npm run build:dev"
  publish = "build_local"